#############################################################################
# Makefile for building: ServoController
# Generated by qmake (2.01a) (Qt 4.7.0) on: Wed Jan 12 12:19:14 2011
# Project:  ServoController.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug -o Makefile ServoController.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -D_TTY_POSIX_ -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/main.cpp \
		src/mainwindow.cpp \
		src/win_qextserialport.cpp \
		src/qextserialport.cpp \
		src/qextserialenumerator.cpp \
		src/qextserialbase.cpp \
		src/posix_qextserialport.cpp moc_mainwindow.cpp \
		moc_win_qextserialport.cpp \
		moc_qextserialport.cpp \
		moc_qextserialbase.cpp
OBJECTS       = main.o \
		mainwindow.o \
		win_qextserialport.o \
		qextserialport.o \
		qextserialenumerator.o \
		qextserialbase.o \
		posix_qextserialport.o \
		moc_mainwindow.o \
		moc_win_qextserialport.o \
		moc_qextserialport.o \
		moc_qextserialbase.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		ServoController.pro
QMAKE_TARGET  = ServoController
DESTDIR       = 
TARGET        = ServoController

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ServoController.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug -o Makefile ServoController.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug -o Makefile ServoController.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/ServoController1.0.0 || $(MKDIR) .tmp/ServoController1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/ServoController1.0.0/ && $(COPY_FILE) --parents src/mainwindow.h src/win_qextserialport.h src/qextserialport.h src/qextserialenumerator.h src/qextserialbase.h src/posix_qextserialport.h .tmp/ServoController1.0.0/ && $(COPY_FILE) --parents src/main.cpp src/mainwindow.cpp src/win_qextserialport.cpp src/qextserialport.cpp src/qextserialenumerator.cpp src/qextserialbase.cpp src/posix_qextserialport.cpp .tmp/ServoController1.0.0/ && $(COPY_FILE) --parents src/mainwindow.ui .tmp/ServoController1.0.0/ && (cd `dirname .tmp/ServoController1.0.0` && $(TAR) ServoController1.0.0.tar ServoController1.0.0 && $(COMPRESS) ServoController1.0.0.tar) && $(MOVE) `dirname .tmp/ServoController1.0.0`/ServoController1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/ServoController1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_win_qextserialport.cpp moc_qextserialport.cpp moc_qextserialbase.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_win_qextserialport.cpp moc_qextserialport.cpp moc_qextserialbase.cpp
moc_mainwindow.cpp: src/qextserialport.h \
		src/posix_qextserialport.h \
		src/qextserialbase.h \
		src/win_qextserialport.h \
		src/mainwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/mainwindow.h -o moc_mainwindow.cpp

moc_win_qextserialport.cpp: src/qextserialbase.h \
		src/win_qextserialport.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/win_qextserialport.h -o moc_win_qextserialport.cpp

moc_qextserialport.cpp: src/posix_qextserialport.h \
		src/qextserialbase.h \
		src/win_qextserialport.h \
		src/qextserialport.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/qextserialport.h -o moc_qextserialport.cpp

moc_qextserialbase.cpp: src/qextserialbase.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/qextserialbase.h -o moc_qextserialbase.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: src/mainwindow.ui
	/usr/bin/uic-qt4 src/mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: src/main.cpp src/mainwindow.h \
		src/qextserialport.h \
		src/posix_qextserialport.h \
		src/qextserialbase.h \
		src/win_qextserialport.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

mainwindow.o: src/mainwindow.cpp src/mainwindow.h \
		src/qextserialport.h \
		src/posix_qextserialport.h \
		src/qextserialbase.h \
		src/win_qextserialport.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o src/mainwindow.cpp

win_qextserialport.o: src/win_qextserialport.cpp src/win_qextserialport.h \
		src/qextserialbase.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o win_qextserialport.o src/win_qextserialport.cpp

qextserialport.o: src/qextserialport.cpp src/qextserialport.h \
		src/posix_qextserialport.h \
		src/qextserialbase.h \
		src/win_qextserialport.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qextserialport.o src/qextserialport.cpp

qextserialenumerator.o: src/qextserialenumerator.cpp src/qextserialenumerator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qextserialenumerator.o src/qextserialenumerator.cpp

qextserialbase.o: src/qextserialbase.cpp src/qextserialbase.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qextserialbase.o src/qextserialbase.cpp

posix_qextserialport.o: src/posix_qextserialport.cpp src/posix_qextserialport.h \
		src/qextserialbase.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o posix_qextserialport.o src/posix_qextserialport.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_win_qextserialport.o: moc_win_qextserialport.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_win_qextserialport.o moc_win_qextserialport.cpp

moc_qextserialport.o: moc_qextserialport.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qextserialport.o moc_qextserialport.cpp

moc_qextserialbase.o: moc_qextserialbase.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qextserialbase.o moc_qextserialbase.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

